services:
  - type: web
    name: bookequalizer-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        sync: false
      - key: ENVIRONMENT
        value: production